# -*- coding: utf-8 -*-
"""naeunencoder2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxYkqF2q0A0YhdlkbjwOD-BSNn-eQk0i
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/VinAIResearch/COVID19Tweet.git
# %cd COVID19Tweet
!unzip -q WNUT-2020-Task-2-Dataset.zip -d data
!find data -type f

# 1. 함수 가져오기
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, classification_report #정확도, 점수, 성능표 보기

# 2. 데이터 읽기
train_df = pd.read_csv("data/WNUT-2020-Task-2-Dataset/train.tsv", sep="\t") #탭으로 나눠져있음
valid_df = pd.read_csv("data/WNUT-2020-Task-2-Dataset/valid.tsv", sep="\t", header=None)
valid_df.columns = ['Id', 'Text', 'Label'] #헤더가 없다고 함 + 열 이름 할당하게 되어 이름도 다시 할당

# 3. 데이터 확인
train_df.head()
train_df.columns
train_df.shape

# test 데이터 읽기
test_df = pd.read_csv("data/WNUT-2020-Task-2-Dataset/test.tsv", sep="\t", header=None)
test_df.columns = ["Id", "Text", "Label"]

#인코더 가져오기

!pip install -q transformers datasets accelerate emoji==0.6.0
import torch
import numpy as np
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding
from sklearn.metrics import accuracy_score, f1_score, classification_report
# 라벨 숫자 변환
label2id = {
    "UNINFORMATIVE": 0,
    "INFORMATIVE": 1
}

id2label = {
    0: "UNINFORMATIVE",
    1: "INFORMATIVE"
}

train_bert = train_df[["Text", "Label"]].dropna().copy()
valid_bert = valid_df[["Text", "Label"]].dropna().copy()
test_bert = test_df[["Text", "Label"]].dropna().copy()

train_bert["labels"] = train_bert["Label"].map(label2id)
valid_bert["labels"] = valid_bert["Label"].map(label2id)
test_bert["labels"] = test_bert["Label"].map(label2id)
# 코로나 트윗 특화 인코더
model_name = "vinai/bertweet-covid19-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)

m1_model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    id2label=id2label,
    label2id=label2id
)

#인코더는 프리즈
for param in m1_model.base_model.parameters():
    param.requires_grad = False

#토큰화 하기
train_dataset = Dataset.from_pandas(train_bert[["Text", "labels"]], preserve_index=False)
valid_dataset = Dataset.from_pandas(valid_bert[["Text", "labels"]], preserve_index=False)
test_dataset = Dataset.from_pandas(test_bert[["Text", "labels"]], preserve_index=False)
def tokenize(batch):
    return tokenizer(
        batch["Text"],
        truncation=True,
        max_length=128
    )

train_tokenized = train_dataset.map(tokenize, batched=True, remove_columns=["Text"])
valid_tokenized = valid_dataset.map(tokenize, batched=True, remove_columns=["Text"])
test_tokenized = test_dataset.map(tokenize, batched=True, remove_columns=["Text"])

#학습 코드
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "informative_f1": f1_score(labels, preds, pos_label=1),
        "macro_f1": f1_score(labels, preds, average="macro")
    }

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

training_args = TrainingArguments(
    output_dir="./m1_bertweet_covid_freeze",
    learning_rate=1e-3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    save_strategy="no",
    report_to="none"
)

trainer = Trainer(
    model=m1_model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=valid_tokenized,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

#테스트 결과
print("VALID 결과")
valid_result = trainer.evaluate(valid_tokenized)
print(valid_result)

print("TEST 결과")
test_result = trainer.evaluate(test_tokenized)
print(test_result)